### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Ciudan** [bropines/Ballon-translator-portable#1]
how can I change the application language?

**Comment by bropines** [comment]
> how can I change the application language?

Did I forget to remove Russian? I'll fix the config now, thanks for the help

![image](https://github.com/bropines/Ballon-translator-portable/assets/57861007/896827f0-fa10-4015-a0b5-b583ea23d2e0)

**Comment by bropines** [comment]
> > how can I change the application language?
> 
> Did I forget to remove Russian? I'll fix the config now, thanks for the help
> 
> ![image](https://user-images.githubusercontent.com/57861007/270130558-896827f0-fa10-4015-a0b5-b583ea23d2e0.png)

https://huggingface.co/bropines/ballon-translator-models/resolve/main/config.json

It is advisable that you replace your config file with this one, it has support for winOCR Japanese. The default language is English now

**Comment by Ciudan** [comment]
perfect thanks

**Comment by bropines** [comment]
> perfect thanks

Are there any other questions?

**Comment by Ciudan** [comment]
no thanks again
