### ISSUE TITLE
Can the author please add EasyOCR to better support the translation of English comics? Is it possible to save the recognized original text and translated Chinese in separate txt files? 

### ISSUE THREAD

**Issue by asdads123** [bropines/Ballon-translator-portable#2]
Can the author please add EasyOCR to better support the translation of English comics? Is it possible to save the recognized original text and translated Chinese in separate txt files?
请求作者大大可以增加一个EasyOCR来更好支持英文漫画的翻译吗？可以增加将识别的原文和翻译后的中文单独保存在txt文件中吗？

**Comment by bropines** [comment]
Use google OCR. I don't have time to make this change to the main repository yet.

**Comment by bropines** [comment]
in the morning I will fill in the fix of the current google ocr

**Comment by bropines** [comment]
> Is it possible to save the recognized original text and translated Chinese in separate txt files?

Already added

>Can the author please add EasyOCR to better support the translation of English comics?

Use Google OCR. I'll close ISSUE so it doesn't become an eyesore
